run.exe : main.c
	gcc -g -Wall -I/home/RatBot/learning/Stolyarov-A.V.-problems-and-studies/Utilities/Headers \
	/home/RatBot/learning/Stolyarov-A.V.-problems-and-studies/Utilities/Src/my_string.c \
	/home/RatBot/learning/Stolyarov-A.V.-problems-and-studies/Utilities/Src/utilities_functions.c \
	/home/RatBot/learning/Stolyarov-A.V.-problems-and-studies/Utilities/Src/my_list.c main.c -o run.exe