run.exe : main.c
	gcc -g -Wall -DVARIANT_a main.c -o run.exe

a : main.c
	gcc -g -Wall -DVARIANT_$@ main.c -o run.exe

b : main.c
	gcc -g -Wall -DVARIANT_$@ main.c -o run.exe

c : main.c
	gcc -g -Wall -DVARIANT_$@ main.c -o run.exe

d : main.c
	gcc -g -Wall -DVARIANT_$@ main.c -o run.exe